"""
Black-Scholes market: Merton's closed-form solution and its exact
coincidence with the continuous-time duality theorem of Chapter 4.

The Black-Scholes model is complete, so |M_e(S)| = 1: the market has
a unique equivalent martingale measure, and the enlarged dual domain
of Chapter 4 plays no role. This is exactly the setting in which
Merton's original dynamic-programming solution and the
Kramkov-Schachermayer martingale-duality solution must agree, and
this module implements both sides so that the agreement can be
checked pathwise (not merely in distribution), as done in
Experiment 1 (Chapter 7).

Notation (single risky asset, riskless rate r, drift mu, volatility
sigma, CRRA utility U(x) = x^alpha/alpha):

- theta = (mu - r) / sigma                     : market price of risk
- Z_T   = exp(-theta*W_T - 0.5*theta^2*T)       : dQ/dP  (P-Brownian W)
- H_T   = exp(-r*T) * Z_T                       : state-price density
- pi*   = (mu - r) / (sigma^2 * (1 - alpha))    : Merton's constant-mix proportion

Two independent computations of the time-T wealth generated from x0
are provided:

1. ``merton_terminal_wealth``: the exact solution of the wealth SDE
   under the constant-mix strategy pi* (a closed-form function of
   W_T, since pi* is constant -- no time discretisation is needed or
   introduced);
2. ``dual_terminal_wealth``: the first-order condition of the duality
   theorem, X_T_hat = I(y * H_T), with y calibrated analytically so
   that the budget constraint E[H_T * X_T_hat] = x0 holds exactly.

These two must coincide *pathwise*, for every realisation of W_T, up
to floating-point error -- see ``tests/test_merton_validation.py``.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from optiport.utility import CRRAUtility


@dataclass(frozen=True)
class BlackScholesMarket:
    """Single risky asset, geometric Brownian motion, constant riskless
    rate r, drift mu and volatility sigma (all under the physical
    measure P).
    """

    mu: float
    sigma: float
    r: float

    def __post_init__(self):
        if self.sigma <= 0:
            raise ValueError("sigma must be positive.")

    @property
    def theta(self) -> float:
        """Market price of risk, theta = (mu - r) / sigma."""
        return (self.mu - self.r) / self.sigma

    def merton_optimal_pi(self, utility: CRRAUtility) -> float:
        """Merton's constant-mix optimal proportion invested in the
        risky asset, pi* = (mu - r) / (sigma^2 * (1 - alpha)).
        """
        return (self.mu - self.r) / (self.sigma**2 * (1.0 - utility.alpha))

    def state_price_density(self, W_T: np.ndarray, T: float) -> np.ndarray:
        """H_T = exp(-r*T) * dQ/dP, with dQ/dP the unique equivalent
        martingale measure's density (Girsanov), as a function of the
        terminal value W_T of the driving P-Brownian motion.
        """
        theta = self.theta
        Z_T = np.exp(-theta * W_T - 0.5 * theta**2 * T)
        return np.exp(-self.r * T) * Z_T

    def merton_terminal_wealth(
        self, x0: float, utility: CRRAUtility, T: float, W_T: np.ndarray
    ) -> np.ndarray:
        """Exact terminal wealth generated by Merton's constant-mix
        strategy pi*, as a closed-form function of W_T (the constant-
        mix wealth SDE has an explicit solution, since pi* does not
        depend on time or on the state).
        """
        pi_star = self.merton_optimal_pi(utility)
        drift = self.r + pi_star * (self.mu - self.r) - 0.5 * pi_star**2 * self.sigma**2
        return x0 * np.exp(drift * T + pi_star * self.sigma * W_T)

    def calibrate_dual_multiplier(
        self, x0: float, utility: CRRAUtility, T: float
    ) -> float:
        """Closed-form calibration of the Lagrange multiplier y solving
        the budget constraint E[H_T * I(y*H_T)] = x0, for CRRA utility,
        using the analytic moment formula
        E[H_T^p] = exp(-r*T*p) * exp(0.5*p*(p-1)*theta^2*T).
        """
        alpha = utility.alpha
        theta = self.theta
        p = alpha / (alpha - 1.0)
        E_Hp = np.exp(-self.r * T * p) * np.exp(0.5 * p * (p - 1.0) * theta**2 * T)
        return (x0 / E_Hp) ** (alpha - 1.0)

    def dual_terminal_wealth(
        self, x0: float, utility: CRRAUtility, T: float, W_T: np.ndarray
    ) -> np.ndarray:
        """Terminal wealth prescribed by the duality first-order
        condition X_T_hat = I(y * H_T), with y calibrated by
        ``calibrate_dual_multiplier``.
        """
        y = self.calibrate_dual_multiplier(x0, utility, T)
        H_T = self.state_price_density(W_T, T)
        return utility.I(y * H_T)

    def merton_value_function(self, x0: float, utility: CRRAUtility, T: float) -> float:
        """Merton's closed-form value function.
        alpha != 0:  J(0,x0) = x0^alpha/alpha * exp(alpha*k*T)
        alpha  = 0:  J(0,x0) = log(x0) + k*T
        k = r + (mu - r)^2 / (2 * sigma^2 * (1 - alpha)), obtained by
        direct verification of the HJB equation for CRRA utility in
        the Black-Scholes model.
        """
        alpha = utility.alpha
        k = self.r + (self.mu - self.r) ** 2 / (2.0 * self.sigma**2 * (1.0 - alpha))
        if np.isclose(alpha, 0.0):
            return np.log(x0) + k * T
        return x0**alpha / alpha * np.exp(alpha * k * T)

    def expected_utility_constant_mix(
        self, x0: float, utility: CRRAUtility, T: float, pi: float
    ) -> float:
        """Closed-form expected CRRA utility E[U(X_T)] of an *arbitrary*
        constant-mix strategy pi (not necessarily Merton-optimal),
        under the real market dynamics (mu, sigma, r). Used in the
        constrained setting (Chapter 5) to quantify the utility cost
        of a sub-optimal, constraint-compliant proportion pi:

            alpha != 0:  E[U(X_T)] = x0^alpha/alpha
                * exp( alpha*(r + pi*(mu-r) - 0.5*pi^2*sigma^2)*T
                       + 0.5*alpha^2*pi^2*sigma^2*T )
            alpha  = 0:  E[U(X_T)] = log(x0)
                + (r + pi*(mu-r) - 0.5*pi^2*sigma^2)*T
              (log is linear in W_T, so E[W_T] = 0 removes the
              variance-correction term present for alpha != 0).
        """
        alpha = utility.alpha
        drift = self.r + pi * (self.mu - self.r) - 0.5 * pi**2 * self.sigma**2
        if np.isclose(alpha, 0.0):
            return np.log(x0) + drift * T
        return (
            x0**alpha
            / alpha
            * np.exp(alpha * drift * T + 0.5 * alpha**2 * pi**2 * self.sigma**2 * T)
        )
